package bean;
// Generated 14/09/2023 13:29:20 by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * KvmCliente generated by hbm2java
 */
@Entity
@Table(name="kvm_cliente"
    ,catalog="db_kelvin_morel"
)
public class KvmCliente  implements java.io.Serializable {


     private int idKvmCliente;
     private String kvmNome;
     private String kvmSobrenome;
     private String kvmSexo;
     private String kvmRg;
     private String kvmCpf;
     private Date kvmNascimentol;
     private String kvmEmail;
     private String kvmTelefone;
     private String kvmCelular;
     private String kvmCep;
     private String kvmEndereco;
     private String kvmBairro;
     private String kvmCidade;
     private String kvmEstadoCivil;

    public KvmCliente() {
    }

	
    public KvmCliente(int idKvmCliente) {
        this.idKvmCliente = idKvmCliente;
    }
    public KvmCliente(int idKvmCliente, String kvmNome, String kvmSobrenome, String kvmSexo, String kvmRg, String kvmCpf, Date kvmNascimentol, String kvmEmail, String kvmTelefone, String kvmCelular, String kvmCep, String kvmEndereco, String kvmBairro, String kvmCidade, String kvmEstadoCivil) {
       this.idKvmCliente = idKvmCliente;
       this.kvmNome = kvmNome;
       this.kvmSobrenome = kvmSobrenome;
       this.kvmSexo = kvmSexo;
       this.kvmRg = kvmRg;
       this.kvmCpf = kvmCpf;
       this.kvmNascimentol = kvmNascimentol;
       this.kvmEmail = kvmEmail;
       this.kvmTelefone = kvmTelefone;
       this.kvmCelular = kvmCelular;
       this.kvmCep = kvmCep;
       this.kvmEndereco = kvmEndereco;
       this.kvmBairro = kvmBairro;
       this.kvmCidade = kvmCidade;
       this.kvmEstadoCivil = kvmEstadoCivil;
    }
   
     @Id 

    
    @Column(name="id_kvm_cliente", unique=true, nullable=false)
    public int getIdKvmCliente() {
        return this.idKvmCliente;
    }
    
    public void setIdKvmCliente(int idKvmCliente) {
        this.idKvmCliente = idKvmCliente;
    }

    
    @Column(name="kvm_nome", length=45)
    public String getKvmNome() {
        return this.kvmNome;
    }
    
    public void setKvmNome(String kvmNome) {
        this.kvmNome = kvmNome;
    }

    
    @Column(name="kvm_sobrenome", length=45)
    public String getKvmSobrenome() {
        return this.kvmSobrenome;
    }
    
    public void setKvmSobrenome(String kvmSobrenome) {
        this.kvmSobrenome = kvmSobrenome;
    }

    
    @Column(name="kvm_sexo", length=45)
    public String getKvmSexo() {
        return this.kvmSexo;
    }
    
    public void setKvmSexo(String kvmSexo) {
        this.kvmSexo = kvmSexo;
    }

    
    @Column(name="kvm_rg", length=45)
    public String getKvmRg() {
        return this.kvmRg;
    }
    
    public void setKvmRg(String kvmRg) {
        this.kvmRg = kvmRg;
    }

    
    @Column(name="kvm_cpf", length=45)
    public String getKvmCpf() {
        return this.kvmCpf;
    }
    
    public void setKvmCpf(String kvmCpf) {
        this.kvmCpf = kvmCpf;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="kvm_nascimentol", length=10)
    public Date getKvmNascimentol() {
        return this.kvmNascimentol;
    }
    
    public void setKvmNascimentol(Date kvmNascimentol) {
        this.kvmNascimentol = kvmNascimentol;
    }

    
    @Column(name="kvm_email", length=45)
    public String getKvmEmail() {
        return this.kvmEmail;
    }
    
    public void setKvmEmail(String kvmEmail) {
        this.kvmEmail = kvmEmail;
    }

    
    @Column(name="kvm_telefone", length=45)
    public String getKvmTelefone() {
        return this.kvmTelefone;
    }
    
    public void setKvmTelefone(String kvmTelefone) {
        this.kvmTelefone = kvmTelefone;
    }

    
    @Column(name="kvm_celular", length=45)
    public String getKvmCelular() {
        return this.kvmCelular;
    }
    
    public void setKvmCelular(String kvmCelular) {
        this.kvmCelular = kvmCelular;
    }

    
    @Column(name="kvm_cep", length=45)
    public String getKvmCep() {
        return this.kvmCep;
    }
    
    public void setKvmCep(String kvmCep) {
        this.kvmCep = kvmCep;
    }

    
    @Column(name="kvm_endereco", length=45)
    public String getKvmEndereco() {
        return this.kvmEndereco;
    }
    
    public void setKvmEndereco(String kvmEndereco) {
        this.kvmEndereco = kvmEndereco;
    }

    
    @Column(name="kvm_bairro", length=45)
    public String getKvmBairro() {
        return this.kvmBairro;
    }
    
    public void setKvmBairro(String kvmBairro) {
        this.kvmBairro = kvmBairro;
    }

    
    @Column(name="kvm_cidade", length=45)
    public String getKvmCidade() {
        return this.kvmCidade;
    }
    
    public void setKvmCidade(String kvmCidade) {
        this.kvmCidade = kvmCidade;
    }

    
    @Column(name="kvm_estadoCivil", length=45)
    public String getKvmEstadoCivil() {
        return this.kvmEstadoCivil;
    }
    
    public void setKvmEstadoCivil(String kvmEstadoCivil) {
        this.kvmEstadoCivil = kvmEstadoCivil;
    }

    public Object getKvmNascimento1() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }




}


