package bean;
// Generated 14/09/2023 13:29:20 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * KvmUsuarioId generated by hbm2java
 */
@Embeddable
public class KvmUsuarioId  implements java.io.Serializable {


     private int idKvmUsuario;
     private int kvmNivel;

    public KvmUsuarioId() {
    }

    public KvmUsuarioId(int idKvmUsuario, int kvmNivel) {
       this.idKvmUsuario = idKvmUsuario;
       this.kvmNivel = kvmNivel;
    }
   


    @Column(name="id_kvm_usuario", nullable=false)
    public int getIdKvmUsuario() {
        return this.idKvmUsuario;
    }
    
    public void setIdKvmUsuario(int idKvmUsuario) {
        this.idKvmUsuario = idKvmUsuario;
    }


    @Column(name="kvm_nivel", nullable=false)
    public int getKvmNivel() {
        return this.kvmNivel;
    }
    
    public void setKvmNivel(int kvmNivel) {
        this.kvmNivel = kvmNivel;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof KvmUsuarioId) ) return false;
		 KvmUsuarioId castOther = ( KvmUsuarioId ) other; 
         
		 return (this.getIdKvmUsuario()==castOther.getIdKvmUsuario())
 && (this.getKvmNivel()==castOther.getKvmNivel());
   }
   

}


