package bean;
// Generated 14/09/2023 13:29:20 by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * KvmUsuario generated by hbm2java
 */
@Entity
@Table(name="kvm_usuario"
    ,catalog="db_kelvin_morel"
)
public class KvmUsuario  implements java.io.Serializable {


     private KvmUsuarioId id;
     private String kvmNome;
     private String kvmSobrenome;
     private String kvmCpf;
     private Date kvmNascimento;
     private String kvmEmail;
     private String kvmCelular;
     private String kvmSenha;
     private String kvmAtivo;

    public KvmUsuario() {
    }

	
    public KvmUsuario(KvmUsuarioId id) {
        this.id = id;
    }
    public KvmUsuario(KvmUsuarioId id, String kvmNome, String kvmSobrenome, String kvmCpf, Date kvmNascimento, String kvmEmail, String kvmCelular, String kvmSenha, String kvmAtivo) {
       this.id = id;
       this.kvmNome = kvmNome;
       this.kvmSobrenome = kvmSobrenome;
       this.kvmCpf = kvmCpf;
       this.kvmNascimento = kvmNascimento;
       this.kvmEmail = kvmEmail;
       this.kvmCelular = kvmCelular;
       this.kvmSenha = kvmSenha;
       this.kvmAtivo = kvmAtivo;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="idKvmUsuario", column=@Column(name="id_kvm_usuario", nullable=false) ), 
        @AttributeOverride(name="kvmNivel", column=@Column(name="kvm_nivel", nullable=false) ) } )
    public KvmUsuarioId getId() {
        return this.id;
    }
    
    public void setId(KvmUsuarioId id) {
        this.id = id;
    }

    
    @Column(name="kvm_nome", length=45)
    public String getKvmNome() {
        return this.kvmNome;
    }
    
    public void setKvmNome(String kvmNome) {
        this.kvmNome = kvmNome;
    }

    
    @Column(name="kvm_sobrenome", length=45)
    public String getKvmSobrenome() {
        return this.kvmSobrenome;
    }
    
    public void setKvmSobrenome(String kvmSobrenome) {
        this.kvmSobrenome = kvmSobrenome;
    }

    
    @Column(name="kvm_cpf", length=45)
    public String getKvmCpf() {
        return this.kvmCpf;
    }
    
    public void setKvmCpf(String kvmCpf) {
        this.kvmCpf = kvmCpf;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="kvm_nascimento", length=10)
    public Date getKvmNascimento() {
        return this.kvmNascimento;
    }
    
    public void setKvmNascimento(Date kvmNascimento) {
        this.kvmNascimento = kvmNascimento;
    }

    
    @Column(name="kvm_email", length=45)
    public String getKvmEmail() {
        return this.kvmEmail;
    }
    
    public void setKvmEmail(String kvmEmail) {
        this.kvmEmail = kvmEmail;
    }

    
    @Column(name="kvm_celular", length=10)
    public String getKvmCelular() {
        return this.kvmCelular;
    }
    
    public void setKvmCelular(String kvmCelular) {
        this.kvmCelular = kvmCelular;
    }

    
    @Column(name="kvm_senha", length=20)
    public String getKvmSenha() {
        return this.kvmSenha;
    }
    
    public void setKvmSenha(String kvmSenha) {
        this.kvmSenha = kvmSenha;
    }

    
    @Column(name="kvm_ativo", length=1)
    public String getKvmAtivo() {
        return this.kvmAtivo;
    }
    
    public void setKvmAtivo(String kvmAtivo) {
        this.kvmAtivo = kvmAtivo;
    }




}


