package bean;
// Generated 14/09/2023 13:29:20 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * KvmVendaJogo generated by hbm2java
 */
@Entity
@Table(name="kvm_venda_jogo"
    ,catalog="db_kelvin_morel"
)
public class KvmVendaJogo  implements java.io.Serializable {


     private int idKvmVendaJogo;
     private KvmJogos kvmJogos;
     private KvmVenda kvmVenda;
     private String kvmQuantidade;
     private String kvmConfirmado;
     private String kvmCodigoDoJogo;

    public KvmVendaJogo() {
    }

	
    public KvmVendaJogo(int idKvmVendaJogo) {
        this.idKvmVendaJogo = idKvmVendaJogo;
    }
    public KvmVendaJogo(int idKvmVendaJogo, KvmJogos kvmJogos, KvmVenda kvmVenda, String kvmQuantidade, String kvmConfirmado, String kvmCodigoDoJogo) {
       this.idKvmVendaJogo = idKvmVendaJogo;
       this.kvmJogos = kvmJogos;
       this.kvmVenda = kvmVenda;
       this.kvmQuantidade = kvmQuantidade;
       this.kvmConfirmado = kvmConfirmado;
       this.kvmCodigoDoJogo = kvmCodigoDoJogo;
    }
   
     @Id 

    
    @Column(name="id_kvm_venda_jogo", unique=true, nullable=false)
    public int getIdKvmVendaJogo() {
        return this.idKvmVendaJogo;
    }
    
    public void setIdKvmVendaJogo(int idKvmVendaJogo) {
        this.idKvmVendaJogo = idKvmVendaJogo;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="fk_kvm_jogos")
    public KvmJogos getKvmJogos() {
        return this.kvmJogos;
    }
    
    public void setKvmJogos(KvmJogos kvmJogos) {
        this.kvmJogos = kvmJogos;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="fk_kvm_venda")
    public KvmVenda getKvmVenda() {
        return this.kvmVenda;
    }
    
    public void setKvmVenda(KvmVenda kvmVenda) {
        this.kvmVenda = kvmVenda;
    }

    
    @Column(name="kvm_quantidade", length=45)
    public String getKvmQuantidade() {
        return this.kvmQuantidade;
    }
    
    public void setKvmQuantidade(String kvmQuantidade) {
        this.kvmQuantidade = kvmQuantidade;
    }

    
    @Column(name="kvm_confirmado", length=1)
    public String getKvmConfirmado() {
        return this.kvmConfirmado;
    }
    
    public void setKvmConfirmado(String kvmConfirmado) {
        this.kvmConfirmado = kvmConfirmado;
    }

    
    @Column(name="kvm_codigoDoJogo", length=10)
    public String getKvmCodigoDoJogo() {
        return this.kvmCodigoDoJogo;
    }
    
    public void setKvmCodigoDoJogo(String kvmCodigoDoJogo) {
        this.kvmCodigoDoJogo = kvmCodigoDoJogo;
    }




}


