package bean;
// Generated 14/09/2023 13:29:20 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * KvmVenda generated by hbm2java
 */
@Entity
@Table(name="kvm_venda"
    ,catalog="db_kelvin_morel"
)
public class KvmVenda  implements java.io.Serializable {


     private int idKvmVenda;
     private String kvmDataHora;
     private String kvmEndereco;
     private String kvmVendedor;
     private String kvmVendaJogos;
     

    public KvmVenda() {
    }

	
    public KvmVenda(int idKvmVenda) {
        this.idKvmVenda = idKvmVenda;
    }
    public KvmVenda(int idKvmVenda, String kvmDataHora, String kvmEndereco, String kvmVendedor, String kvmVendaJogos) {
       this.idKvmVenda = idKvmVenda;
       this.kvmDataHora = kvmDataHora;
       this.kvmEndereco = kvmEndereco;
       this.kvmVendedor = kvmVendedor;
       this.kvmVendaJogos = kvmVendaJogos;
    
    }
   
     @Id 

    
    @Column(name="id_kvm_venda", unique=true, nullable=false)
    public int getIdKvmVenda() {
        return this.idKvmVenda;
    }
    
    public void setIdKvmVenda(int idKvmVenda) {
        this.idKvmVenda = idKvmVenda;
    }

    
    @Column(name="kvm_dataHora", length=45)
    public String getKvmDataHora() {
        return this.kvmDataHora;
    }
    
    public void setKvmDataHora(String kvmDataHora) {
        this.kvmDataHora = kvmDataHora;
    }

    
    @Column(name="kvm_endereco", length=45)
    public String getKvmEndereco() {
        return this.kvmEndereco;
    }
    
    public void setKvmEndereco(String kvmEndereco) {
        this.kvmEndereco = kvmEndereco;
    }

    
    @Column(name="kvm_vendedor", length=45)
    public String getKvmVendedor() {
        return this.kvmVendedor;
    }
    
    public void setKvmVendedor(String kvmVendedor) {
        this.kvmVendedor = kvmVendedor;
    }

    
    @Column(name="kvm_venda_jogos", length=45)
    public String getKvmVendaJogos() {
        return this.kvmVendaJogos;
    }
    
    public void setKvmVendaJogos(String kvmVendaJogos) {
        this.kvmVendaJogos = kvmVendaJogos;
    }




}


